In [ ]:
import torch
import numpy as np

In [2]:
a = torch.empty(5)
a

tensor([-2.2360e-08,  1.9282e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00])

In [3]:
b = torch.ones([2,3])
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [4]:
c = torch.rand([2,3])
c

tensor([[0.5089, 0.4249, 0.1557],
        [0.6133, 0.2229, 0.9664]])

In [5]:
d= torch.tensor([2,3,4,7])
print(d)
print(d.size())
print(d.shape ) 

tensor([2, 3, 4, 7])
torch.Size([4])
torch.Size([4])


In [6]:
a = np.array([2,3,4,7])
a

array([2, 3, 4, 7])

In [7]:
e = d.view(2,2)
e

tensor([[2, 3],
        [4, 7]])

In [8]:
e=e.numpy()
print(type(e))

<class 'numpy.ndarray'>


In [9]:
e=  torch.from_numpy(e)

In [10]:
print(type(e))

<class 'torch.Tensor'>


In [11]:
a+1

array([3, 4, 5, 8])

In [12]:
a*2

array([ 4,  6,  8, 14])

In [13]:
e.view(-1,4)

tensor([[2, 3, 4, 7]])

In [14]:
# a.numpy()

In [15]:
# a =torch.from_numpy(a)

In [16]:
a= torch.from_numpy(a)
a

tensor([2, 3, 4, 7], dtype=torch.int32)

In [17]:
a+d

tensor([ 4,  6,  8, 14])

In [18]:
torch.add(a,d)

tensor([ 4,  6,  8, 14])

In [19]:
a.add_(d)

tensor([ 4,  6,  8, 14], dtype=torch.int32)

In [20]:
torch.sub(a,d)

tensor([2, 3, 4, 7])

In [21]:
torch.mul(a,d)

tensor([ 8, 18, 32, 98])

In [22]:
d = torch.tensor(d[:],dtype=torch.int32)

C:\Users\pushp\AppData\Local\Temp\ipykernel_39092\2469169900.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  d = torch.tensor(d[:],dtype=torch.int32)


In [23]:
a

tensor([ 4,  6,  8, 14], dtype=torch.int32)

In [24]:
torch.mul(a,d)

tensor([ 8, 18, 32, 98], dtype=torch.int32)

In [25]:
torch.dot(a,d)

tensor(156, dtype=torch.int32)

In [26]:
d.view(-1,4)

tensor([[2, 3, 4, 7]], dtype=torch.int32)

In [27]:
a.view(-1,4)

tensor([[ 4,  6,  8, 14]], dtype=torch.int32)

In [28]:
z=torch.matmul(d,a)
z

tensor(156, dtype=torch.int32)

In [29]:
x= torch.tensor([2,3,4,5])

In [30]:
y= torch.tensor([1,3,63,2])

In [31]:
x.to(dtype=torch.float32)

tensor([2., 3., 4., 5.])

In [32]:
y.to(torch.float32)

tensor([ 1.,  3., 63.,  2.])

In [33]:
x= torch.tensor(x[:],requires_grad=True)

C:\Users\pushp\AppData\Local\Temp\ipykernel_39092\1725364222.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x= torch.tensor(x[:],requires_grad=True)


RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [34]:
a=np.array([2,3])

In [35]:
a.dtype=np.float32

In [36]:
y.clone().detach().requires_grad=True
y

RuntimeError: only Tensors of floating point and complex dtype can require gradients

In [37]:
x.clone().requires_grad_=True

In [38]:
z=x+y

In [39]:
print(z.grad_fn)

None


In [40]:
z*5

tensor([ 15,  30, 335,  35])

In [41]:
z= y**3
z

tensor([     1,     27, 250047,      8])

In [42]:
a= torch.tensor([2,3,5],dtype = torch.float32,requires_grad=True)
a

tensor([2., 3., 5.], requires_grad=True)

In [43]:
b = a+2
b

tensor([4., 5., 7.], grad_fn=<AddBackward0>)

In [44]:
print(b.grad_fn)

In [45]:
c=b*b*2
print(c)
c_mean=c.mean()
c_mean

tensor([32., 50., 98.], grad_fn=<MulBackward0>)


tensor(60., grad_fn=<MeanBackward0>)

In [46]:
#This method will not work as backward() i.e backward propogation uses scalar 
c.backward() 

RuntimeError: grad can be implicitly created only for scalar outputs

In [47]:
c_mean.backward()

In [48]:
print(a.grad) #dc_mean/da

tensor([5.3333, 6.6667, 9.3333])


In [49]:
y= 2*a

In [50]:
for _ in range(10):
    y=y*2

In [51]:
y.shape

torch.Size([3])

In [52]:
z=torch.tensor([0.03,0.0003,.1])

In [53]:
y.backward(torch.tensor([1,1,1]))

In [54]:
a.grad

tensor([2053.3333, 2054.6667, 2057.3333])

In [55]:
a = torch.randn(2, 2)
print(a.requires_grad)
b = ((a * 3) / (a - 1))
print(b.grad_fn)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
None
True


In [56]:
a = torch.randn(2, 2, requires_grad=True)
print(a.requires_grad)
print(a)
b = a.detach()
print(b.requires_grad)
b+=2
print(a) #Here if we try to change 1 value then the other value also changes so in place of this it is suggested to use .clone() method
print(b)

True
tensor([[ 0.6408, -3.2057],
        [-0.6499,  0.5874]], requires_grad=True)
False
tensor([[ 2.6408, -1.2057],
        [ 1.3501,  2.5874]], requires_grad=True)
tensor([[ 2.6408, -1.2057],
        [ 1.3501,  2.5874]])


In [57]:
a = torch.randn(2, 2, requires_grad=True)
print(a.requires_grad)
with torch.no_grad():
    print((a ** 2).requires_grad)
    print(a**2)

True
False
tensor([[0.0053, 0.1702],
        [0.9355, 0.8959]])


In [ ]:
w = torch.ones(4,requires_grad= True)
for epoch in range(3):
    wt_pred = (w*2).sum()
    wt_pred.backward()
    print(w.grad)
    w.detach()
    with torch.no_grad():
        w -= 0.1 * w.grad
        
    w.grad.zero_()
print(w)
print(wt_pred)